Catch a broader set of exceptions in `Session` constructor
My previous commit did not completely fix the leak.  The Resource Leak
Checker saw that AssertionError is also possible:

    ./daikon/simplify/Session.java:116: error: [builder:required.method.not.called] @MustCall method close may not have been invoked on trace_file or any of its aliases.
            trace_file = new PrintStream(new FileOutputStream(f));
                       ^
      The type of object is: java.io.PrintStream.
      Reason for going out of scope: possible exceptional exit due to null with exception type java.lang.AssertionError